DROP TABLE MYMEMBER;
DROP SEQUENCE MYNOSQ;

--�����ȣ, ���̵�, ��й�ȣ, �̸�, �ּ�, ��ȭ��ȣ, �̸���, ���Կ���(����Y/Ż��N), ���(ADMIN, USER,...)

CREATE SEQUENCE MYNOSQ;

CREATE TABLE MYMEMBER(
MYNO NUMBER NOT NULL,
MYID VARCHAR2(500) NOT NULL,
MYPW VARCHAR2(500) NOT NULL,
MYNAME VARCHAR2(1000) NOT NULL,
MYADDR VARCHAR2(2000) NOT NULL,
MYPHONE VARCHAR2(20) NOT NULL,
MYEMAIL VARCHAR2(100) NOT NULL,
MYENABLED VARCHAR2(2) NOT NULL,
MYROLE VARCHAR2(20) NOT NULL,
CONSTRAINT MYMEMBER_PK PRIMARY KEY (MYNO),
CONSTRAINT MYMEMBER_UQ UNIQUE(MYID, MYPHONE, MYEMAIL),
CONSTRAINT MYMEMBER_ENABLED_CHK CHECK(MYENABLED IN ('Y','N'))
);

INSERT INTO MYMEMBER VALUES (MYNOSQ.NEXTVAL, 'ADMIN','ADMIN1234','������','������ʹ�','010','ASD','Y','ADMIN');
INSERT INTO MYMEMBER VALUES (MYNOSQ.NEXTVAL, 'ADMINN','ADMIN1234','����1','���Ծ ��','010-1234-5678','ASDl@naver.com','Y','ADMIN');
INSERT INTO MYMEMBER VALUES (MYNOSQ.NEXTVAL, 'user11','ADMIN1234','���׳׽�','���θ���','010-1234-5678','ASD1l@naver.com','Y','USER');
INSERT INTO MYMEMBER VALUES (MYNOSQ.NEXTVAL, 'ADMINNN','ADMIN1234','����1','���Ծ ��','010-1234-5678','ASDl@naver.com','Y','ADMIN');

SELECT * FROM MYMEMBER;